EvaluatorBundle\Entity\Course:
    type: entity
    repositoryClass: EvaluatorBundle\Repository\CourseRepository
    table: courses
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    oneToMany:
        student:
            targetEntity: Student
            mappedBy: idCourse
            cascade: ["persist"]
        partial:
            targetEntity: Partial
            mappedBy: idCourse
            cascade: ["persist"]          
    lifecycleCallbacks: {  }
