EvaluatorBundle\Entity\Student:
    type: entity
    repositoryClass: EvaluatorBundle\Repository\StudentRepository
    table: students
    indexes:
        fk_students_courses:
            columns:
                - id_course
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        idCourse:
            targetEntity: Course
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: Student
            joinColumns:
                id_course:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
