<?php

namespace Proxies\__CG__\EvaluatorBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mark extends \EvaluatorBundle\Entity\Mark implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EvaluatorBundle\\Entity\\Mark' . "\0" . 'id', '' . "\0" . 'EvaluatorBundle\\Entity\\Mark' . "\0" . 'grade', '' . "\0" . 'EvaluatorBundle\\Entity\\Mark' . "\0" . 'idCourse', '' . "\0" . 'EvaluatorBundle\\Entity\\Mark' . "\0" . 'idPartial', '' . "\0" . 'EvaluatorBundle\\Entity\\Mark' . "\0" . 'idStudent'];
        }

        return ['__isInitialized__', '' . "\0" . 'EvaluatorBundle\\Entity\\Mark' . "\0" . 'id', '' . "\0" . 'EvaluatorBundle\\Entity\\Mark' . "\0" . 'grade', '' . "\0" . 'EvaluatorBundle\\Entity\\Mark' . "\0" . 'idCourse', '' . "\0" . 'EvaluatorBundle\\Entity\\Mark' . "\0" . 'idPartial', '' . "\0" . 'EvaluatorBundle\\Entity\\Mark' . "\0" . 'idStudent'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mark $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrade($grade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrade', [$grade]);

        return parent::setGrade($grade);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrade', []);

        return parent::getGrade();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCourse(\EvaluatorBundle\Entity\Course $idCourse = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCourse', [$idCourse]);

        return parent::setIdCourse($idCourse);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCourse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCourse', []);

        return parent::getIdCourse();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPartial(\EvaluatorBundle\Entity\Partial $idPartial = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPartial', [$idPartial]);

        return parent::setIdPartial($idPartial);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPartial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPartial', []);

        return parent::getIdPartial();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdStudent(\EvaluatorBundle\Entity\Student $idStudent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdStudent', [$idStudent]);

        return parent::setIdStudent($idStudent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdStudent', []);

        return parent::getIdStudent();
    }

}
